{% set name = "CairoSVG" %}
{% set version = "2.1.3" %}
{% set sha256 = "e512f555f576b6462b04b585c4ba4c09a43f3a8fec907b60ead21d7d00c550e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [not py3k or win]
  entry_points:
    - {{ name|lower }}={{ name|lower }}:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - cairocffi
    - lxml
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml
  run:
    - python
    # needed for import of pkg_resources
    - setuptools
    - cairocffi
    - lxml
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml

test:
  imports:
    - cairosvg
  commands:
    - cairosvg --help > /dev/null

about:
  home: http://www.cairosvg.org/
  license: LGPLv3+
  summary: 'A Simple SVG Converter based on Cairo'
  license_family: LGPL
  license_file: COPYING
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
