{% set name = "CairoSVG" %}
{% set version = "2.0.3" %}
{% set sha256 = "d6e39c00267ec946ae0b7c08cb18fc781fba1ed63f6eda8f4428a4245485472e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not py3k or win]
  entry_points:
    - {{ name|lower }}={{ name|lower }}:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cairocffi
    - lxml
    - cssselect
    - pillow
    - tinycss
  run:
    - python
    # needed for import of pkg_resources
    - setuptools
    - cairocffi
    - lxml
    - cssselect
    - pillow
    - tinycss

test:
  imports:
    - cairosvg
  commands:
    - cairosvg --help > /dev/null

about:
  home: http://www.cairosvg.org/
  license: LGPLv3+
  summary: 'A Simple SVG Converter based on Cairo'
  license_family: LGPL
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
