{% set name = "CairoSVG" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66f333ef5dc79fdfbd3bbe98adc791b1f854e0461067d202fa7b15de66d517ec

build:
  number: 0
  skip: true  # [py2k]
  entry_points:
    - cairosvg = cairosvg.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - cairocffi
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml

test:
  imports:
    - cairosvg
  commands:
    - cairosvg --help

about:
  home: http://www.cairosvg.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A Simple SVG Converter based on Cairo'
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
