appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UueEZfE0AaA6xdmN63pXETaN4sngTlWqHb60muFqb8i0Ni8J+OCISSiUXm0KHweDyaFAhGvHXAQS2Itimg9HQ/UGHP601Wq7c2Yz4ugPRt492QDKa4ga1A7IKaTe+jXj1qmDhkExtuXwUmong7WNSL0gz9i/xuUI0Cz2wocsY0/k80YAAA3RtW1JJeX57Ae3y4bFIOa78ej9ds0UfV0TbvEG4J2/bkQ+Shyo2zfOD3Ylzujc9fUcIkb8YLtXM0vX1bejAOsHiai/NjEVpYrvFdR0bBsPvqjoW4Ng24UZqsnSy3TIATPFlKEizzLT9S+CqshB8Mq91B4WbGVqEEagHLbjgYNzdTZpCl87FTWHe3RUYkNnVG3+rhXLK39GOFC3TXARimAVDb4vdYD0LXJtRVSt7uVT1WtapvR0WfGYOFHzTFZlD5jr30NaE5FMBbL/KftD2Bda2/X6wsX1fO0t/o1UHN3ffB8OWzDLFOujn/lt9GpzISOGXZwwVdG2HGLWholk+CBYrYdQM0JZy/SgB31/xoagjPMeiaeSGvBzUqm2OVy0x/kew4i6q/uWmKrbEJ+C0JuuFk0vn/Im14OFec4o6CEBJzm6/m/RS303TlAUIAdYucS9AgiNwcJLv6CWiM/1NU7Q03jEeIezoRwLpgDo/Tb2fY/5GFrRXeNoAWE=}
provider:
  win: azure
conda_forge_output_validation: true
