travis:
  secure:
    BINSTAR_TOKEN: KgtJdroNOhIaA7ceJIsCUtp8+/sXkbOi2K/23QeqUjAaoyZ5KR34uZYx/KnAwuk/NUlgmBQqAb1jmelCtQz/tFImF0Z6Cc7MTNQOPLS8JrNFMwwT2wugrDxHZkQph0xJv+ZihlEBDjjodsPVHZOOvaUQR8NWBZ6N6vKyrdgnukBA5s/QslMjRB8lbDE6PJkGU62v4wHUBdwacuxI4FzfJJHDZPuYt7fL+jSXKQmGvTzcvABgs/tptZQgu+ZiPFPx1ETBnMILBQkK88blAZXBWgUS3zVoXcIZzAgwzmqx+My8T5cdTU6lwmrDMg6jZD+F9cuVkD0i4m+cJUH32SSUb7xprxfWqg/Px1Yu+M7T4SYA6DC1p2TGpofpLx3yP64O5hxJo6F/73oxVJiKosqcfPrjE+qjTf2yGzRGESh3WLlOZrnhsdVhh7Jz2XaJXUWoWnUXfiT0aIt33LP2rXe5PzQvE2ptQpQwPBFCQ78WUjC1JicrD7lvNy1bLr3/d7aPQ2RfQgIirdF41Xb5ju5tb0JZ7Ju6hLKqtgsaoi4OKtXdIRkgnibORaDfL0voksAOElWZa+rIKvberBsrGImKQYeTfc7UrM0hlRic1zPnKZs6xv+WW11y1XBg9XHSsJzCCIISf3swOxKruIcE+lvRb9NhMJ+lrkW2XzuXcIQaAGc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
