travis:
  secure:
    BINSTAR_TOKEN: PSW9Xiv3soHGU30cNLhnHSB1J6ZK8UqKyQj8hEbcHs5wz1Tacijd82wRmB2tvcVbOxA2Yc8voX1aPD0y2oSDEh3S5IywRfCUpmr6WdbV8aO34NJC8HLVJVIsrm0ECRSnhamYOpOXYYKpi5uWq7MRVhbBfjTRM6mw9PYhf4Xrx5U5/1l4C8zDs1Xfd2IvA+P3h2XrOEkzjB/+ctANqzNx+ynUIhSJ9QKsnn8fUpi5G7PcEiPr6HJD0riTkOBnGZz+2/iPzPEZlSEjBhzuvUVqcJEMU4itD1oLkFTxpbv616y7cbrujc3WOwEFyezhccZQIQGXgW8iWd76iTwHHSolVonD5eU26WU6PWOLO9jSoup3lUhzrbT4SK7Dnr60yaYdaWjwz1Jh2Q22+O6EafAVLMUcYgKwWh5Ol1MfJ97OUEWtZsvYuB4jZLXAciKae3wB/kqpRaOv5NCBlQMJ71YPMlWOJia1dDAxl2faJRDNuw5neBv/lZWMG/YtQTMHnBnj1XZDo8QlOw0tJcsskJEjZj8JrhBMwLVvqB5dUM71P1RWgRgr2EvgWZUQE/z4EbwnZu5MVruL5L2VhowRu5yBLzypTXYGIDt211hxiaX7vQ6r+nfTEyKdu8Ui+3zmd9H4YigTZ47AFWN3JZOCBEfgaSeTU+Idq2aiT9novgoPXNc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
